print ("1.for add")
print("2. for divide")
print ("3. for multiply")
print("4. for subtract")
print("5. for root")
print ("6. for percent")
oper =int(input("Выберите число"))
a = int(input("Выберите первое число:"))
b = int(input("Выберите второе число:"))